name: Build and push to deploy (Hostinger)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build -- --base=/
      - name: Publish dist to deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy $(date -u +'%Y-%m-%d %H:%M:%S')"
          git branch -M deploy
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/sphynx-crypto/Gringerberg-website.git
          git push -f origin deploy
